map $ssl_preread_server_name $soundsible_tls_upstream {
    turn.84-247-161-82.sslip.io 127.0.0.1:5349;
    default 127.0.0.1:8443;
}

server {
    listen 84.247.161.82:443;
    proxy_pass $soundsible_tls_upstream;
    ssl_preread on;
}
