import { locale, type Locale } from './i18n';

const en = {
  eyebrow: 'Spotify · Apple Music · Soundsible',
  title: 'Move your music',
  intro: 'Bring your library and playlists with you. Soundsible reuses songs you already have, then finds only what is missing.',
  chooseSource: 'Where is your music now?',
  chooseSourceHint: 'Choose a service and Soundsible will walk you through the rest.',
  spotifySummary: 'Saved songs, favourites and playlists',
  appleSummary: 'Your music library and playlists',
  back: 'Choose another service',
  spotifyTitle: 'Get your music from Spotify',
  spotifyIntro: 'Spotify prepares a copy of your library for you. A free account is enough.',
  spotifyWaitingTitle: 'Waiting for Spotify?',
  spotifyWaitingIntro: 'When Spotify emails you, download the file and come straight back here.',
  spotifyRequestTitle: 'Ask Spotify for your account data',
  spotifyRequestDetail: 'Under Download your data, select Account data. You do not need Extended streaming history.',
  openSpotify: 'Open Spotify',
  spotifyWaitTitle: 'Wait for Spotify’s email',
  spotifyWaitDetail: 'You can close Soundsible. Spotify will tell you when the download is ready.',
  spotifyReturnTitle: 'Download it and return here',
  spotifyReturnDetail: 'Keep the file exactly as Spotify sent it. Do not open or unpack it.',
  officialInstructions: 'See the official instructions',
  appleTitle: 'Get your music from Apple Music',
  appleIntro: 'Export a copy of your library on a computer, then bring that file back to Soundsible.',
  appleDeviceLabel: 'Device with your Apple Music library',
  mobile: 'Phone or tablet',
  appleOpenMusic: 'Open Music on your Mac',
  appleOpenMusicMacDetail: 'Make sure your library and playlists are visible.',
  appleExportTitle: 'Export the complete library',
  appleExportMacDetail: 'In the menu bar, choose File → Library → Export Library.',
  appleSaveTitle: 'Save the file somewhere easy to find',
  appleSaveDetail: 'Your Downloads folder or Desktop works well. Do not open or modify it.',
  appleOpenItunes: 'Open iTunes on your PC',
  appleOpenItunesDetail: 'Use the iTunes library that contains the music and playlists you want to move.',
  appleExportWindowsDetail: 'Choose File → Library → Export Library.',
  appleWindowsNotice: 'Apple currently documents complete library export through iTunes, not the newer Apple Music app for Windows.',
  continueComputer: 'Continue on a computer',
  continueComputerDetail: 'Apple does not offer a complete library export from its phone or tablet app. Open this Soundsible address on a Mac or PC:',
  copyAddress: 'Copy address',
  addressCopied: 'Soundsible address copied',
  copyFailed: 'Could not copy the address',
  chooseSpotifyFile: 'Choose the file Spotify sent you',
  chooseAppleFile: 'Choose the Apple Music file',
  fileHint: 'Leave it exactly as you received or saved it. You can also drop it here.',
  privacy: 'Your file stays on this Soundsible Station and is never sent to us or anyone else.',
  analyzing: 'Reading your library…',
  recent: 'Restoring your unfinished import…',
  badFile: 'That does not look like the expected music-library file. Check the steps and choose the original file again.',
  analyzed: 'Ready to move',
  found: (tracks: number, playlists: number) => `${tracks} songs across ${playlists} playlists`,
  reuse: (count: number) => `${count} already on Soundsible`,
  download: (count: number) => `${count} to find`,
  review: (count: number) => `${count} need a quick check`,
  library: 'Saved library',
  libraryHint: 'Import saved songs into your Soundsible library',
  favourites: (count: number) => `${count} liked songs will stay favourites`,
  playlists: 'Playlists',
  selectAll: 'Select all',
  clear: 'Clear',
  start: 'Start import',
  selected: (count: number) => `${count} unique songs selected`,
  storage: (size: string) => `Up to ${size} if every missing song must be downloaded`,
  moving: 'Moving your music',
  completed: (done: number, total: number) => `${done} of ${total} songs ready`,
  pause: 'Pause',
  resume: 'Resume',
  retry: 'Retry failures',
  cancel: 'Cancel',
  reviewTitle: 'Check doubtful matches',
  reviewHint: 'Soundsible stopped before downloading these. Choose the right result or skip it.',
  use: 'Use this',
  skip: 'Skip',
  noCandidate: 'No reliable candidate was found.',
  done: 'Your music is ready',
  doneHint: 'Playlists kept their original order. Liked Songs were added to Favourites.',
  partial: 'Import finished with gaps',
  partialHint: 'Available songs were imported. You can retry failures or leave unavailable songs skipped.',
  another: 'Import another library',
  openLibrary: 'Open library',
  failed: 'The import stopped unexpectedly.',
};

const es: typeof en = {
  eyebrow: 'Spotify · Apple Music · Soundsible',
  title: 'Mueve tu música',
  intro: 'Trae tu biblioteca y tus playlists. Soundsible reutiliza lo que ya tienes y busca únicamente lo que falta.',
  chooseSource: '¿Dónde tienes ahora tu música?',
  chooseSourceHint: 'Elige un servicio y Soundsible te guiará durante el resto.',
  spotifySummary: 'Canciones guardadas, favoritos y playlists',
  appleSummary: 'Tu biblioteca musical y tus playlists',
  back: 'Elegir otro servicio',
  spotifyTitle: 'Consigue tu música de Spotify',
  spotifyIntro: 'Spotify prepara una copia de tu biblioteca. Una cuenta gratuita es suficiente.',
  spotifyWaitingTitle: '¿Esperando a Spotify?',
  spotifyWaitingIntro: 'Cuando Spotify te escriba, descarga el archivo y vuelve directamente aquí.',
  spotifyRequestTitle: 'Pide a Spotify los datos de tu cuenta',
  spotifyRequestDetail: 'En Descargar tus datos, selecciona Datos de la cuenta. No necesitas el Historial de streaming ampliado.',
  openSpotify: 'Abrir Spotify',
  spotifyWaitTitle: 'Espera el correo de Spotify',
  spotifyWaitDetail: 'Puedes cerrar Soundsible. Spotify te avisará cuando la descarga esté lista.',
  spotifyReturnTitle: 'Descárgalo y vuelve aquí',
  spotifyReturnDetail: 'Conserva el archivo exactamente como te lo envió Spotify. No lo abras ni lo extraigas.',
  officialInstructions: 'Ver las instrucciones oficiales',
  appleTitle: 'Consigue tu música de Apple Music',
  appleIntro: 'Exporta una copia de tu biblioteca desde un ordenador y trae después ese archivo a Soundsible.',
  appleDeviceLabel: 'Dispositivo con tu biblioteca de Apple Music',
  mobile: 'Móvil o tablet',
  appleOpenMusic: 'Abre Música en tu Mac',
  appleOpenMusicMacDetail: 'Comprueba que aparecen tu biblioteca y tus playlists.',
  appleExportTitle: 'Exporta la biblioteca completa',
  appleExportMacDetail: 'En la barra de menús, elige Archivo → Biblioteca → Exportar biblioteca.',
  appleSaveTitle: 'Guarda el archivo en un lugar fácil de encontrar',
  appleSaveDetail: 'La carpeta Descargas o el Escritorio son buenas opciones. No lo abras ni lo modifiques.',
  appleOpenItunes: 'Abre iTunes en tu PC',
  appleOpenItunesDetail: 'Usa la biblioteca de iTunes que contiene la música y las playlists que quieres mover.',
  appleExportWindowsDetail: 'Elige Archivo → Biblioteca → Exportar biblioteca.',
  appleWindowsNotice: 'Apple solo documenta la exportación completa de la biblioteca mediante iTunes, no desde la nueva aplicación Apple Music para Windows.',
  continueComputer: 'Continúa en un ordenador',
  continueComputerDetail: 'Apple no permite exportar la biblioteca completa desde el móvil o la tablet. Abre esta dirección de Soundsible en un Mac o PC:',
  copyAddress: 'Copiar dirección',
  addressCopied: 'Dirección de Soundsible copiada',
  copyFailed: 'No se ha podido copiar la dirección',
  chooseSpotifyFile: 'Elige el archivo que te envió Spotify',
  chooseAppleFile: 'Elige el archivo de Apple Music',
  fileHint: 'Déjalo exactamente como lo recibiste o guardaste. También puedes arrastrarlo aquí.',
  privacy: 'Tu archivo se queda en esta Station de Soundsible y nunca se nos envía a nosotros ni a nadie más.',
  analyzing: 'Leyendo tu biblioteca…',
  recent: 'Recuperando tu importación pendiente…',
  badFile: 'Ese no parece ser el archivo esperado de tu biblioteca. Revisa los pasos y vuelve a elegir el archivo original.',
  analyzed: 'Todo listo para mover',
  found: (tracks: number, playlists: number) => `${tracks} canciones en ${playlists} playlists`,
  reuse: (count: number) => `${count} ya están en Soundsible`,
  download: (count: number) => `${count} por encontrar`,
  review: (count: number) => `${count} necesitan una comprobación`,
  library: 'Biblioteca guardada',
  libraryHint: 'Importa tus canciones guardadas a la biblioteca de Soundsible',
  favourites: (count: number) => `${count} Me gusta conservarán el favorito`,
  playlists: 'Playlists',
  selectAll: 'Todas',
  clear: 'Ninguna',
  start: 'Empezar importación',
  selected: (count: number) => `${count} canciones únicas seleccionadas`,
  storage: (size: string) => `Hasta ${size} si hay que descargar todas las que faltan`,
  moving: 'Moviendo tu música',
  completed: (done: number, total: number) => `${done} de ${total} canciones listas`,
  pause: 'Pausar',
  resume: 'Continuar',
  retry: 'Reintentar fallos',
  cancel: 'Cancelar',
  reviewTitle: 'Comprueba las coincidencias dudosas',
  reviewHint: 'Soundsible se ha detenido antes de descargarlas. Elige el resultado correcto o sáltalo.',
  use: 'Usar esta',
  skip: 'Saltar',
  noCandidate: 'No se ha encontrado una opción fiable.',
  done: 'Tu música está lista',
  doneHint: 'Las playlists conservan su orden. Tus Me gusta se han añadido a Favoritos.',
  partial: 'La importación terminó con huecos',
  partialHint: 'Se ha importado lo disponible. Puedes reintentar los fallos o dejar fuera lo no disponible.',
  another: 'Importar otra biblioteca',
  openLibrary: 'Abrir biblioteca',
  failed: 'La importación se ha detenido inesperadamente.',
};

const fr: typeof en = {
  eyebrow: 'Spotify · Apple Music · Soundsible',
  title: 'Transférez votre musique',
  intro: 'Emportez votre bibliothèque et vos playlists. Soundsible réutilise les morceaux déjà présents et cherche uniquement les autres.',
  chooseSource: 'Où se trouve votre musique actuellement ?',
  chooseSourceHint: 'Choisissez un service et Soundsible vous guidera pour la suite.',
  spotifySummary: 'Titres enregistrés, favoris et playlists',
  appleSummary: 'Votre bibliothèque musicale et vos playlists',
  back: 'Choisir un autre service',
  spotifyTitle: 'Récupérez votre musique depuis Spotify',
  spotifyIntro: 'Spotify prépare une copie de votre bibliothèque. Un compte gratuit suffit.',
  spotifyWaitingTitle: 'Vous attendez Spotify ?',
  spotifyWaitingIntro: 'Lorsque Spotify vous écrit, téléchargez le fichier et revenez directement ici.',
  spotifyRequestTitle: 'Demandez vos données de compte à Spotify',
  spotifyRequestDetail: 'Dans Télécharger vos données, sélectionnez Données du compte. L’historique d’écoute étendu n’est pas nécessaire.',
  openSpotify: 'Ouvrir Spotify',
  spotifyWaitTitle: 'Attendez l’e-mail de Spotify',
  spotifyWaitDetail: 'Vous pouvez fermer Soundsible. Spotify vous préviendra lorsque le téléchargement sera prêt.',
  spotifyReturnTitle: 'Téléchargez-le et revenez ici',
  spotifyReturnDetail: 'Conservez le fichier exactement tel que Spotify l’a envoyé. Ne l’ouvrez pas et ne le décompressez pas.',
  officialInstructions: 'Voir les instructions officielles',
  appleTitle: 'Récupérez votre musique depuis Apple Music',
  appleIntro: 'Exportez une copie de votre bibliothèque sur un ordinateur, puis revenez dans Soundsible avec ce fichier.',
  appleDeviceLabel: 'Appareil contenant votre bibliothèque Apple Music',
  mobile: 'Mobile ou tablette',
  appleOpenMusic: 'Ouvrez Musique sur votre Mac',
  appleOpenMusicMacDetail: 'Vérifiez que votre bibliothèque et vos playlists sont visibles.',
  appleExportTitle: 'Exportez toute la bibliothèque',
  appleExportMacDetail: 'Dans la barre des menus, choisissez Fichier → Bibliothèque → Exporter la bibliothèque.',
  appleSaveTitle: 'Enregistrez le fichier dans un endroit facile à retrouver',
  appleSaveDetail: 'Le dossier Téléchargements ou le Bureau conviennent. Ne l’ouvrez pas et ne le modifiez pas.',
  appleOpenItunes: 'Ouvrez iTunes sur votre PC',
  appleOpenItunesDetail: 'Utilisez la bibliothèque iTunes contenant la musique et les playlists à transférer.',
  appleExportWindowsDetail: 'Choisissez Fichier → Bibliothèque → Exporter la bibliothèque.',
  appleWindowsNotice: 'Apple documente l’export complet de la bibliothèque dans iTunes, mais pas dans la nouvelle app Apple Music pour Windows.',
  continueComputer: 'Continuez sur un ordinateur',
  continueComputerDetail: 'Apple ne permet pas d’exporter toute la bibliothèque depuis un mobile ou une tablette. Ouvrez cette adresse Soundsible sur un Mac ou un PC :',
  copyAddress: 'Copier l’adresse',
  addressCopied: 'Adresse Soundsible copiée',
  copyFailed: 'Impossible de copier l’adresse',
  chooseSpotifyFile: 'Choisissez le fichier envoyé par Spotify',
  chooseAppleFile: 'Choisissez le fichier Apple Music',
  fileHint: 'Conservez-le exactement tel que reçu ou enregistré. Vous pouvez aussi le déposer ici.',
  privacy: 'Votre fichier reste sur cette Station Soundsible et ne nous est jamais envoyé, ni à personne d’autre.',
  analyzing: 'Lecture de votre bibliothèque…',
  recent: 'Récupération de votre importation en cours…',
  badFile: 'Ce fichier ne semble pas être celui attendu. Vérifiez les étapes et choisissez à nouveau le fichier original.',
  analyzed: 'Prêt pour le transfert',
  found: (tracks: number, playlists: number) => `${tracks} titres dans ${playlists} playlists`,
  reuse: (count: number) => `${count} déjà sur Soundsible`,
  download: (count: number) => `${count} à rechercher`,
  review: (count: number) => `${count} à vérifier`,
  library: 'Bibliothèque enregistrée',
  libraryHint: 'Importer les titres enregistrés dans votre bibliothèque Soundsible',
  favourites: (count: number) => `${count} titres aimés resteront favoris`,
  playlists: 'Playlists',
  selectAll: 'Tout sélectionner',
  clear: 'Effacer',
  start: 'Commencer l’importation',
  selected: (count: number) => `${count} titres uniques sélectionnés`,
  storage: (size: string) => `Jusqu’à ${size} si tous les titres manquants doivent être téléchargés`,
  moving: 'Transfert de votre musique',
  completed: (done: number, total: number) => `${done} titres sur ${total} prêts`,
  pause: 'Pause',
  resume: 'Reprendre',
  retry: 'Réessayer les échecs',
  cancel: 'Annuler',
  reviewTitle: 'Vérifiez les correspondances incertaines',
  reviewHint: 'Soundsible s’est arrêté avant leur téléchargement. Choisissez le bon résultat ou ignorez-le.',
  use: 'Utiliser',
  skip: 'Ignorer',
  noCandidate: 'Aucun résultat fiable trouvé.',
  done: 'Votre musique est prête',
  doneHint: 'L’ordre des playlists a été conservé. Les titres aimés ont été ajoutés aux Favoris.',
  partial: 'Importation terminée avec des manques',
  partialHint: 'Les titres disponibles ont été importés. Vous pouvez réessayer les échecs ou ignorer les indisponibles.',
  another: 'Importer une autre bibliothèque',
  openLibrary: 'Ouvrir la bibliothèque',
  failed: 'L’importation s’est arrêtée de manière inattendue.',
};

const zh: typeof en = {
  eyebrow: 'Spotify · Apple Music · Soundsible',
  title: '迁移你的音乐',
  intro: '带上你的资料库和播放列表。Soundsible 会复用已有歌曲，只查找缺少的内容。',
  chooseSource: '你的音乐现在在哪里？',
  chooseSourceHint: '选择一个服务，Soundsible 会引导你完成其余步骤。',
  spotifySummary: '已收藏歌曲、喜爱歌曲和播放列表',
  appleSummary: '音乐资料库和播放列表',
  back: '选择其他服务',
  spotifyTitle: '从 Spotify 获取你的音乐',
  spotifyIntro: 'Spotify 会为你准备资料库副本，免费账户也可以使用。',
  spotifyWaitingTitle: '正在等待 Spotify？',
  spotifyWaitingIntro: '收到 Spotify 邮件后，下载文件并直接回到这里。',
  spotifyRequestTitle: '向 Spotify 申请账户数据',
  spotifyRequestDetail: '在“下载你的数据”中选择“账户数据”，无需选择扩展流媒体历史记录。',
  openSpotify: '打开 Spotify',
  spotifyWaitTitle: '等待 Spotify 的邮件',
  spotifyWaitDetail: '你可以关闭 Soundsible。下载准备好后，Spotify 会通知你。',
  spotifyReturnTitle: '下载后回到这里',
  spotifyReturnDetail: '保持 Spotify 发来的文件原样，不要打开或解压。',
  officialInstructions: '查看官方说明',
  appleTitle: '从 Apple Music 获取你的音乐',
  appleIntro: '在电脑上导出资料库副本，然后把该文件带回 Soundsible。',
  appleDeviceLabel: '存有 Apple Music 资料库的设备',
  mobile: '手机或平板',
  appleOpenMusic: '在 Mac 上打开“音乐”',
  appleOpenMusicMacDetail: '确认可以看到你的资料库和播放列表。',
  appleExportTitle: '导出完整资料库',
  appleExportMacDetail: '在菜单栏中选择“文件”→“资料库”→“导出资料库”。',
  appleSaveTitle: '将文件保存到容易找到的位置',
  appleSaveDetail: '可以保存到“下载”文件夹或桌面。不要打开或修改文件。',
  appleOpenItunes: '在电脑上打开 iTunes',
  appleOpenItunesDetail: '使用包含你想迁移的音乐和播放列表的 iTunes 资料库。',
  appleExportWindowsDetail: '选择“文件”→“资料库”→“导出资料库”。',
  appleWindowsNotice: 'Apple 目前只说明了通过 iTunes 导出完整资料库的方法，新的 Windows 版 Apple Music 应用不支持此说明。',
  continueComputer: '请在电脑上继续',
  continueComputerDetail: 'Apple 不支持从手机或平板导出完整资料库。请在 Mac 或 PC 上打开此 Soundsible 地址：',
  copyAddress: '复制地址',
  addressCopied: '已复制 Soundsible 地址',
  copyFailed: '无法复制地址',
  chooseSpotifyFile: '选择 Spotify 发给你的文件',
  chooseAppleFile: '选择 Apple Music 文件',
  fileHint: '保持收到或保存时的原样。你也可以把文件拖到这里。',
  privacy: '你的文件只保留在这台 Soundsible Station 上，绝不会发送给我们或任何其他人。',
  analyzing: '正在读取你的资料库…',
  recent: '正在恢复未完成的导入…',
  badFile: '这似乎不是预期的音乐资料库文件。请检查步骤并重新选择原始文件。',
  analyzed: '可以开始迁移',
  found: (tracks: number, playlists: number) => `${playlists} 个播放列表，共 ${tracks} 首歌曲`,
  reuse: (count: number) => `${count} 首已在 Soundsible 中`,
  download: (count: number) => `${count} 首需要查找`,
  review: (count: number) => `${count} 首需要确认`,
  library: '已收藏资料库',
  libraryHint: '将收藏的歌曲导入 Soundsible 资料库',
  favourites: (count: number) => `${count} 首喜爱歌曲会保留为“喜爱”`,
  playlists: '播放列表',
  selectAll: '全选',
  clear: '清除',
  start: '开始导入',
  selected: (count: number) => `已选择 ${count} 首不同的歌曲`,
  storage: (size: string) => `如果需要下载所有缺少的歌曲，最多占用 ${size}`,
  moving: '正在迁移你的音乐',
  completed: (done: number, total: number) => `${total} 首歌曲中已有 ${done} 首准备就绪`,
  pause: '暂停',
  resume: '继续',
  retry: '重试失败项',
  cancel: '取消',
  reviewTitle: '检查不确定的匹配',
  reviewHint: 'Soundsible 在下载前暂停了这些歌曲。请选择正确结果或跳过。',
  use: '使用',
  skip: '跳过',
  noCandidate: '未找到可靠结果。',
  done: '你的音乐已准备好',
  doneHint: '播放列表保留了原有顺序，喜爱歌曲已加入“喜爱”。',
  partial: '导入完成，但有部分缺失',
  partialHint: '可用歌曲已导入。你可以重试失败项，或跳过不可用歌曲。',
  another: '导入其他资料库',
  openLibrary: '打开资料库',
  failed: '导入意外停止。',
};

const copy: Record<Locale, typeof en> = { en, es, fr, zh };

export function migrateCopy() {
  return copy[locale()];
}
