import { locale, type Locale } from './i18n';

const en = {
    title: 'Move your music',
    intro: 'Bring your library and playlists with you. Soundsible reuses songs you already have, then finds and downloads only what is missing.',
    drop: 'Choose your export',
    formats: 'Spotify ZIP or JSON · Apple Music XML, TXT or CSV',
    privacy: 'The export stays on this Station. Listening history and podcasts are ignored.',
    spotifyHelp: 'Spotify: request or download your account data, then choose the ZIP or Playlist JSON.',
    appleHelp: 'Apple Music: export your library from Music as XML, or choose its song-list text file.',
    analyzing: 'Reading your library…',
    recent: 'Restoring your unfinished import…',
    badFile: 'Soundsible could not read that export.',
    analyzed: 'Ready to move',
    found: (tracks: number, playlists: number) => `${tracks} songs across ${playlists} playlists`,
    reuse: (count: number) => `${count} already on Soundsible`,
    download: (count: number) => `${count} to find`,
    review: (count: number) => `${count} need a quick check`,
    library: 'Saved library',
    libraryHint: 'Import saved songs into your Soundsible library',
    favourites: (count: number) => `${count} liked songs will stay favourites`,
    playlists: 'Playlists',
    selectAll: 'Select all',
    clear: 'Clear',
    start: 'Start import',
    selected: (count: number) => `${count} unique songs selected`,
    storage: (size: string) => `Up to ${size} if every missing song must be downloaded`,
    moving: 'Moving your music',
    completed: (done: number, total: number) => `${done} of ${total} songs ready`,
    pause: 'Pause',
    resume: 'Resume',
    retry: 'Retry failures',
    cancel: 'Cancel',
    reviewTitle: 'Check doubtful matches',
    reviewHint: 'Soundsible stopped before downloading these. Choose the right result or skip it.',
    use: 'Use this',
    skip: 'Skip',
    noCandidate: 'No reliable candidate was found.',
    done: 'Your music is ready',
    doneHint: 'Playlists kept their original order. Liked Songs were added to Favourites.',
    partial: 'Import finished with gaps',
    partialHint: 'Available songs were imported. You can retry failures or leave unavailable songs skipped.',
    another: 'Import another library',
    openLibrary: 'Open library',
    failed: 'The import stopped unexpectedly.',
};

const es: typeof en = {
    title: 'Mueve tu música',
    intro: 'Trae tu biblioteca y tus playlists. Soundsible reutiliza lo que ya tienes y después busca y descarga solo lo que falta.',
    drop: 'Elige tu exportación',
    formats: 'Spotify ZIP o JSON · Apple Music XML, TXT o CSV',
    privacy: 'La exportación se queda en esta Station. El historial y los podcasts se ignoran.',
    spotifyHelp: 'Spotify: solicita o descarga los datos de tu cuenta y elige el ZIP o el JSON de playlists.',
    appleHelp: 'Apple Music: exporta la biblioteca desde Música como XML, o elige su listado de canciones en texto.',
    analyzing: 'Leyendo tu biblioteca…',
    recent: 'Recuperando tu importación pendiente…',
    badFile: 'Soundsible no ha podido leer esa exportación.',
    analyzed: 'Todo listo para mover',
    found: (tracks: number, playlists: number) => `${tracks} canciones en ${playlists} playlists`,
    reuse: (count: number) => `${count} ya están en Soundsible`,
    download: (count: number) => `${count} por encontrar`,
    review: (count: number) => `${count} necesitan una comprobación`,
    library: 'Biblioteca guardada',
    libraryHint: 'Importa tus canciones guardadas a la biblioteca de Soundsible',
    favourites: (count: number) => `${count} Me gusta conservarán el favorito`,
    playlists: 'Playlists',
    selectAll: 'Todas',
    clear: 'Ninguna',
    start: 'Empezar importación',
    selected: (count: number) => `${count} canciones únicas seleccionadas`,
    storage: (size: string) => `Hasta ${size} si hay que descargar todas las que faltan`,
    moving: 'Moviendo tu música',
    completed: (done: number, total: number) => `${done} de ${total} canciones listas`,
    pause: 'Pausar',
    resume: 'Continuar',
    retry: 'Reintentar fallos',
    cancel: 'Cancelar',
    reviewTitle: 'Comprueba las coincidencias dudosas',
    reviewHint: 'Soundsible se ha detenido antes de descargarlas. Elige el resultado correcto o sáltalo.',
    use: 'Usar esta',
    skip: 'Saltar',
    noCandidate: 'No se ha encontrado una opción fiable.',
    done: 'Tu música está lista',
    doneHint: 'Las playlists conservan su orden. Tus Me gusta se han añadido a Favoritos.',
    partial: 'La importación terminó con huecos',
    partialHint: 'Se ha importado lo disponible. Puedes reintentar los fallos o dejar fuera lo no disponible.',
    another: 'Importar otra biblioteca',
    openLibrary: 'Abrir biblioteca',
    failed: 'La importación se ha detenido inesperadamente.',
};

const copy: Record<Locale, typeof en> = { en, es, fr: en, zh: en };

export function migrateCopy() {
  return copy[locale()];
}
